mymima/facts/urls.py
from django.urls import path

from . import views

app_name = "facts"

urlpatterns = [
    path('', views.home, name="home"),
    path('artist/<str:let>', views.artists, name="artists"),
    path('song/<str:let>', views.songs, name="songs"),
    path('song_artist/<str:name>', views.songs_by_artist, name="song_by_artist"),
    path('facts/<str:song>/<str:artist>', views.facts, name="facts"),
    path('search', views.search, name="search"),
    path('add/', views.add_fact, name="add")
    ]

mymima/mymima/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('facts.urls')),

]

mymima/facts/models.py
import datetime

from django.db import models
from django.utils import timezone


class Artist(models.Model):
    name = models.CharField(max_length=200)
    pub_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.name}'


class Song(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, related_name='songs')
    name = models.CharField(max_length=200)
    pub_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.name}'

class Facts(models.Model):
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    fact = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.fact}'

mymima/facts/forms.py
from django import forms

from . import models
from .models import Song



class CreateFact(forms.Form):
    artist = forms.CharField(max_length=100, label='אומן')
    # date = forms.DateField(label='תאריך')
    song = forms.CharField(max_length=100, label='שיר')
    # songs = forms.ModelChoiceField(queryset=Song.objects.order_by('name'), label='בחר שיר')
    fact = forms.CharField(widget=forms.Textarea(), label='תיאור')

mymima/facts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages
from django.core.mail import mail_admins
from django.shortcuts import render, redirect
from . import templates, forms

# Create your views here.
# from .forms import Search
from .forms import CreateFact
from .models import Artist, Song, Facts

letters = []
for x in range(1488, 1515):
    if x != 1498 and x != 1503 and x != 1507 and x != 1509 and x != 1501:
        letters.append(chr(x))


def home(request):
    context = {'letters': letters,
               'request': request,
               }
    return render(request, 'facts/home_page.html', context)


def artists(request, let):
    artist_list = []
    for artist in Artist.objects.order_by('name'):
        if artist.name:
            if artist.name[0] == let:
                artist_list.append(artist.name)
    context = {
        'let': let,
        'count': len(artist_list),
        'letters': letters,
        'artist_list': artist_list
    }
    return render(request, 'facts/artists.html', context)


def songs(request, let):
    songs_list = []
    for song in Song.objects.order_by('name'):
        if song.name:
            if song.name[0] == let:
                songs_list.append((song.name, song.artist.name))
    context = {
        'let': let,
        'count': len(songs_list),
        'letters': letters,
        'artist_list': songs_list
    }
    return render(request, 'facts/song.html', context)


def songs_by_artist(request, name):
    songs = []
    for song in Song.objects.order_by('name'):
        if song.artist.name == name:
            songs.append((song.name, name))
    context = {'songs': songs, 'letters': letters, 'count': len(songs), 'name': name}
    return render(request, 'facts/songs_by_artist.html', context)


def facts(request, song, artist):
    facts = []
    colors = ['#CCFFCC', '#EDF3FE']
    print(len(song))
    i = 0
    for fact in Facts.objects.all():
        if fact.song.name == song:
            facts.append((fact.fact, colors[i % 2]))
            i += 1
    context = {'facts': facts,
               'artist': artist,
               'letters': letters,
               'name': song
               }
    return render(request, 'facts/facts.html', context)


def search(request):
    colors = ['#CCFFCC', '#EDF3FE']
    fact_color = []
    i = 0
    # if request.method == "GET":
    letter = request.GET.get('q')
    artist = []
    song = []
    fact = []
    if letter:
        artist = Artist.objects.filter(name__contains=letter)
        song = Song.objects.filter(name__contains=letter)
        fact = Facts.objects.filter(fact__contains=letter)
        for fa in fact:
            fact_color.append((fa, colors[i % 2]))
            i += 1
    return render(request, "facts/search.html", {
        'letters': letters,
        'artists': artist,
        'songs': song,
        'facts': fact_color,
    })


def add_fact(request):
    if request.method == 'POST':
        print('y')
        form = CreateFact(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            o, b = Artist.objects.get_or_create(name=data['artist'])
            o.save()
            o1 = Song(name=data['song'], artist=o)
            if not Song.objects.filter(name=data['song']):
                o1.save()
                o2, b = Facts.objects.get_or_create(song=o1, fact=data['fact'])
                o2.save()
            # q = CreateFact(name=form['name'], date=form['date'], fact=form['fact'],)

    form = CreateFact()

    return render(request, 'facts/add_fact.html', {
        'form': form,
        'letters': letters
    })

mymima/facts/templates/base.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet"
          href="{% static "css/base.css" %}">
    <title>{% block title %}PO TIDCHUF TITLE{% endblock %}</title>
</head>

<body>
<div class="navbar">
    <a href="/">
        <img src="{% static 'images/logo.png' %}" alt="logo">
    </a>
    <form action="{% url 'facts:search' %}" method="get">
        <input type="text" align="right" id="searchbar" name="q" value="{{ request.GET.q }}">
        <input type="submit" value="הולכת מחפשת" id="">
    </form>
</div>
<div class="container">
    <div class="artist">
        <p>
            חפש לפי שם אמן:
        </p>
        <table border="0">
            <tr>
                 {% for let in letters %}
                    <td bgcolor="#CCFFCC"><a href="/artist/{{ let }}">{{ let }}</a></td>
                {% endfor %}

            </tr>
        </table>
    </div>
    <div class="song">
        <p>
            חפש לפי שם שיר:

        <table border="0">
            <tr>
                 {% for let in letters %}
                    <td bgcolor="#FFCCCC"><a href="/song/{{ let }}">{{ let }}</a></td>
                {% endfor %}
            </tr>
        </table>
    </div>
</div>

{% block content %}PO TIDCHUF CONTENT{% endblock %}
<footer>
    <a href="{% url 'facts:add' %}"> הוסף עובדה חדשה </a> &nbsp;<!-- <a href="ask.php"> שאל את מימה </a> &nbsp; -->
    <a href="#">שאלות ללא תשובות </a> &nbsp;
    <a href="#"> מה חדש </a> &nbsp;
    <a href="#"><b> תפתיעי אותי </b></a> &nbsp;
    <a href="{% url 'facts:home' %}"> דף ראשי </a> &nbsp;
    <br>
    <p class="psico">
        <a href="#"> RSS</a> &nbsp;
        <a href="#"> תנאי שימוש</a> &nbsp;
        <a href="#" > פסיכולוגית</a> &nbsp;
        <a href="#" > פסיכולוג </a> &nbsp;
        <a href="#"> תודות</a> &nbsp;
        <a href="#"> צור קשר</a>
    </p>
    <br>
    מימה, 2020</center>


</footer>


</body>

</html>

mymima/facts/templates/facts/add_fact.html
{% extends "base.html" %}
{% block title %}
    עובדה חדשה
{% endblock %}
{% block content %}
    <div
            style="height: 10px" class="artist_found">
    </div>

    <div>
        <h1>הוסף עובדה חדשה</h1>
        <form action="" method="post">
            {% csrf_token %}
            <ul>
                {{ form.as_p }}
            </ul>
            <button style="margin-right: 80%">שלח עובדה</button>

        </form>
    </div>


{% endblock %}

mymima/facts/templates/facts/artists.html
{% extends "base.html" %}
{% block title %}
    אומנים
{% endblock %}
{% block content %}
    <div class="artist_found">
    מצאנו {{count}} אמנים שמתחילים באות {{let}}:
    </div>
    <div>
    {% for artist in artist_list %}
        <p><a href="{% url 'facts:song_by_artist' artist %}">{{ artist }}</a></p>
    {% endfor %}
    </div>
{% endblock %}

mymima/facts/templates/facts/facts.html
{% extends "base.html" %}
{% block title %}
    {{ name }}
{% endblock %}
{% block content %}
    <div style="height: 10px" class="artist_found">
    </div>
    <div>
        <h1>{{ name }}</h1>
        <h2>{{ artist }}</h2>
    <div class="fact">
        {% for fact in facts %}
            <p style="background-color: {{ fact.1 }}">{{ fact.0 }}</p>
        {% endfor %}
    </div>

    </div>
{% endblock %}

mymima/facts/templates/facts/home_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/home_page.css' %}">
    <meta charset="UTF-8">
    <title>Mima</title>
</head>
<body>
<div class="center">
    <a href="/">
        <img src="{% static 'images/logo.png' %}" alt="logo">
    </a>
{#    <form method="post" novalidate>#}
{#        {% csrf_token %}#}
{#        <ul>#}
{#            {{ form.as_ul }}#}
{#        </ul>#}
{#        <button>הולכת מחפשת</button>#}
{#    </form>#}
    <form action="{% url 'facts:search' %}" method="get">
        <input type="text" align="right" id="searchbar" name="q" value="{{ request.GET.q }}">
        <input type="submit" value="הולכת מחפשת" id="">
    </form>
    <p>
        דפדף לפי שם אמן:
        <br>
    <div>
        <table border="0" align="center">
            <tr>
                {% for let in letters %}
                    <td bgcolor="#CCFFCC"><a href="{% url 'facts:artists' let %}">{{ let }}</a></td>
                {% endfor %}
            </tr>
        </table>
    </div>
    <p>
        דפדף לפי שם שיר:
        <br>

    <table border="0" align="center">
        <tr>
            {% for let in letters %}
                <td bgcolor="#FFCCCC"><a href="{% url 'facts:songs' let %}">{{ let }}</a></td>
            {% endfor %}

        </tr>
    </table>

    <p>
        <a href="{% url 'facts:add' %}"> הוסף עובדה חדשה </a> &nbsp;<!-- <a href="ask.php"> שאל את מימה </a> &nbsp; -->
        <a href="#">שאלות ללא תשובות </a> &nbsp;
        <a href="#"> מה חדש </a> &nbsp;
        <a href="#"><b> תפתיעי אותי </b></a> &nbsp;
        <br>
    <p class="psico">
        <a href="#"> RSS</a> &nbsp;
        <a href="#"> תנאי שימוש</a> &nbsp;
        <a href="#" > פסיכולוגית</a> &nbsp;
        <a href="#"> פסיכולוג </a> &nbsp;
        <a href="#"> תודות</a> &nbsp;
        <a href="#"> צור קשר</a>
    <p>
        <br>
        מימה, 2020</center>

</div>


</body>
</html>

mymima/facts/templates/facts/search.html
{% extends "base.html" %}
{% block title %}
    תוצאות חיפוש
{% endblock %}
{% block content %}
    <div
            style="height: 10px" class="artist_found">
    </div>
    <div>
        <h2>תוצאות באמנים</h2>
        {% for artist in artists %}
            <p><a href="{% url 'facts:song_by_artist' artist %}">{{ artist }}</a></p>
        {% endfor %}
    </div>
    <div>
        <h2>תוצאות בשירים</h2>
        {% for song in songs %}
            <p><a href="/facts/{{ song }}/{{ song.artist }}">{{ song }}</a> - {{ song.artist }}</p>
        {% endfor %}
    </div>
    <div>
        <h2>עובדות שקשורות:</h2>
        {% for fact in facts %}
            <p style="background-color: {{ fact.1 }}; width: 60%">
            <a href="/facts/{{ fact.0.song }}/{{ fact.0.song.artist }}">{{ fact.0.song }}</a> - {{ fact.0.song.artist }}
                <br>
                {{ fact.0 }}
            </p>
        {% endfor %}
    </div>
{% endblock %}

mymima/facts/templates/facts/song.html
{% extends "base.html" %}
{% block title %}
    שירים
{% endblock %}
{% block content %}
    <div class="artist_found">
    מצאנו {{count}} שירים שמתחילים באות {{let}}:
    </div>
    <div>
    {% for song in artist_list %}
        <p><a href="/facts/{{ song.0 }}/{{ song.1 }}">{{ song.0 }}</a> - {{ song.1 }}</p>
    {% endfor %}
    </div>
{% endblock %}

mymima/facts/templates/facts/songs_by_artist.html
{% extends "base.html" %}
{% block title %}
    {{ name }}
{% endblock %}
{% block content %}
    <div class="artist_found">
        נמצאו {{ count }} שירים
    </div>
    <div>
        {% for song in songs %}
            <p><a href="/facts/{{ song.0 }}/{{ song.1 }}">{{ song.0 }}</a></p>
        {% endfor %}
    </div>
{% endblock %}